### PR TITLE
adds katon article

### PR DESCRIPTION
**Pull request by kylemac**
i'm really liking [katon](https://github.com/typicode/katon) and it's decently helpful for having a lot of roots projects at the same time and for SPA's - so I wrote a little article about it. 

would love to have someone give me some editorial support.

### CODE REVIEW

**Comment by kylemac** [comment]
thanks for being editor @jenius

**Comment by hhsnopek** [comment]
@kylemac I updated the codeblocks for styling purposes, very minor :smile:
Great article, just setup katon because of it!

**Comment by kylemac** [comment]
Great! Hope you like it

**Comment by jenius** [comment]
Can we rebase this on top of master?

**Comment by kylemac** [comment]
done

**Comment by jenius** [comment]
Thank ya! Going to try to push out new releases of accord, roots, and merge this today :grinning:

**Pull request merged**
