### PR TITLE
Add article on Roots integration with Gulp

### PR DESCRIPTION
**Pull request by michaelkornblum**
Hi Jeff,
  I just finished writing an article on how to integrate Roots with a new or existing Gulp configuration. This is a rough draft. If you like what you see, please drop me a line and I will make the necessary edits so it can go live on the website. I'm looking forward to your input. Have a great day.

### CODE REVIEW

**Comment by jenius** [comment]
Great article and great work on setting this up. Have you thought about creating a gulp plugin that abstracts this functionality? I think if we had something like this, I would approve of adding it as an article, it would make things much simpler for people and involve even less boilerplate, which is always our goal with roots.

**Comment by michaelkornblum** [comment]
Hi Jeff.
Thanks for the review and positive feedback to my article. At this time,
there are no plans to turn the content of my submission into a gulp plugin.
The reason that I didn't find the idea feasible is largely because I feel
that doing such a plugin would result in an unneeded duplication of effort.

With Gulp's rich ecosystem of tens of thousands of plugins, the community
has started to blacklist contributions that either duplicate past efforts,
can be  implemented in simple JavaScript, or are downright unusable. One
such plugin that was similar to the one you requested was gulp-jekyll. The
reason gulp-jekyll was blacklisted was because the task could have been
implemented using another plugin called gulp-spawn, or through the use of a
vanilla Node.js child process.

What I could suggest to make our user's lives easier is to take another
look into https://github.com/michaelkornblum/juice-bar, as I have improved
the documentation to make the project usable. Additionally, there is a gulp
recipes github page that I can make a pull request to where the work I've
done thus far cam also be thoroughly documented.

With this being said, how would you envision a gulp plugin for roots going
forward? I'm not completely opposed to the idea, I just want to see our
respective projects succeed.

One again, I thank you for your time, review and positive feedback.

PS: Recently you wrote an article for carrot about using roots with dynamic
content to create a simple blog. In the article you showed a sort function
that took a javascript object that looked like this:

- each post in sort(site.posts, { by: 'date' })

What other arguments and parameters does that sort function have? I'm
looking into using roots as my blog platform of choice, and want to see how
far I can push the static site paradigm. Thanks again.

**Comment by jenius** [comment]
Hey sorry for the delay here, I'll deal with this today and get it merged up!

**Comment by jenius** [comment]
Awesome, and great points. So could you potentially add a reference to this repo to the conclusion of the article, then I think we're good for merge?

As far as the sort function, it's something that used to ship with roots core but was removed in the process of compartmentalizing everything. Really, it's nothing more than a simple `Array.sort` function that originally I slightly modified to compare by date when the keyword `date` was found. You could build a function like this for yourself and bring it in as a local quickly and easily!

**Comment by michaelkornblum** [comment]
Sure, Jeff. I will be able to do that on Monday. Currently I'm out of town
and have limited net access. I also want to reference the roots page with
the API as well.

**Comment by michaelkornblum** [comment]
Hi, Jeff. Made the requested changes. I also made some updates to the article so it better reflects my github repo. Hopefully this baby is ready to go to press. Have a great week :)

**Comment by jenius** [comment]
Shipped! http://roots.cx/articles/roots-with-gulp

**Pull request merged**
