### PR TITLE
add wordpress extension

### PR DESCRIPTION
**Pull request by hhsnopek**
@jenius let me know if you'd like the description changed; it was an attempt to be similar to roots-contentful's description.

### CODE REVIEW

**Comment by hhsnopek** [comment]
@jenius, reworded the description

**Comment by jenius** [comment]
Ok we're almost there -- extensions go in here now: https://github.com/carrot/roots-www/blob/master/data/extensions.yaml

**Comment by hhsnopek** [comment]
oh wow I was really behind haha - updated and rebased

**Comment by jenius** [comment]
Whoo! Looks great, thanks :+1:

**Pull request merged**
