### PR TITLE
Open Source Android Hub

### PR DESCRIPTION
**Pull request by argyleink**
place for authors to commit articles via pull requests, nice fun open source blog. thanks for the system architecture roots =)

### CODE REVIEW

**Comment by kylemac** [comment]
@argyleink sweet! do you mind squashing these commits into 1 for us? 

also, we've done a couple projects with roots for intel over here @carrot too

**Comment by argyleink** [comment]
squash them? so your commit history looks clean? wouldnt it just be a PR accept and only 1 file changes at 1 line? i'm down to do some cleanup if you need, but gimme a little more about what you're looking for other than "squashing" =)

**Comment by kylemac** [comment]
yeah, exactly. on this branch, you'd run a `git rebase -i HEAD~3` and then `squash`  (actually technical term, surprisingly) or `fixup` these 3 commits into 1. then you'd force push the changes here. 

i noticed we don't have a `contributing.md` guide for this repo, but we usually do and it talks about commit cleanliness. here's root's `contributing.md` - https://github.com/jenius/roots/blob/master/contributing.md#commit-cleanliness 

heres some reference material about squashing too: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by argyleink** [comment]
damn, 3 years of git, never needed to squash. cool, time to learn something =)

**Comment by argyleink** [comment]
going to submit this from the company i'm at, instead of personal.

**Comment by kylemac** [comment]
:ok_hand:

**Comment by argyleink** [comment]
nice page you guys built for Intel, we pitched them a similar idea this year just to find out it was already done! apparently by you guys! =) small software world huh?

**Comment by kylemac** [comment]
:two_men_holding_hands:

**Pull request closed without merging**
