### PR TITLE
Added URL to js_pipeline for additional information.

### PR DESCRIPTION
**Pull request by nimitzshah**
Decided to make it link to the github page rather than the NPM page for consistency.

### CODE REVIEW

**Comment by kylemac** [comment]
nimit, if you're like me you may be interested why and when github truncates your commit messages with the elipsis (like it has above). we've done the research on this a bunch and it has created a bit of a carrot guide that you might be interested to read. https://gist.github.com/kylemac/e5ddeadb0fa7c9d9000e

**Comment by jenius** [comment]
Looks good, thanks @nimitzshah and good call @kylemac

**Comment by nimitzshah** [comment]
Thanks for the guide!
So would a better message be?:
"Link js_pipeline to Github repo in documentation"

**Comment by kylemac** [comment]
yup - that is a great rewrite

**Pull request merged**
