### PR TITLE
first pass at view documentation.

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
My initial attempt at adding some documentation on different view engines and their locals.

I don't know a lot (they're undocumented!), so there's probably a lot more info a dev could add in here. But I think it's a good base.

### CODE REVIEW

**Comment by jenius** [comment]
Great start, thanks for tackling this. I think for the accord engines, we should add explicit instructions for each one. Like "Roots supports these languages, jade (`npm i jade`, extension `.jade`), etc..."

This would make it most clear for people. Then when we add new engines to accord we'd just have to reflect them here. Worse comes to worse, there's a delay between when accord supports a language and when it's added to the article. Anyone can always contribute these updates if they need. People shouldn't have to dig through the accord source really to find out though.

View has a couple locals built in like `_path`, for example, which is the path from the public roots to the view. These can be really useful, definitely worth documenting.

If I have time I'll add on to this for sure, but I am really strapped for time right now so I can't assure it will be super soon. Either way, this is a great start, and looking forward to seeing more here1

**Comment by SevereOverfl0w** [comment]
Added something a little more manual, used a table, as it was the only decent way to show all the info.

I added a little table styling to make it look a little nicer too. Let me what you think.

**Comment by jenius** [comment]
Screenshot me?

**Comment by SevereOverfl0w** [comment]
ykhnihu

**Comment by jenius** [comment]
Looks good! I might be a bit more explicit with how you set things up here. Like hand-hold the user through the installation through npm, changing of the extension, how to pass through compiler options for that view engine, etc.

Thanks for your great work here, this is looking amazing already!

**Comment by jescalan** [comment]
This has been added to the site through slightly different formatting 💃

**Pull request closed without merging**
