### PR TITLE
Update index.jade

### PR DESCRIPTION
**Pull request by ml242**
Was looking at using Roots after listening to the Javascript Jabber and noticed some typos in the index.

### CODE REVIEW

**Comment by kylemac** [comment]
good catch @ml242. thanks for the help!

**Comment by ml242** [comment]
Thanks for merging in the changes, @kylemac. It makes me want to contribute so much more than when proposals die on the vine for no reason. Really looking forward to trying out Roots on a personal project this weekend. Cheers!

**Comment by kylemac** [comment]
@ml242 - don't hesitate to ask any questions about roots as you test it out. hopefully you'll find us to be responsive -- we love getting people past that initial learning curve and into building fun projects with roots

**Comment by declandewet** [comment]
I can confirm this, the Carrot/Roots team will grow on you if you stick around. :smiley_cat:

**Comment by jenius** [comment]
Thanks @ml242! Really appreciate it. Hope I sounded on on js jabber, and really hope you enjoy roots!

**Pull request merged**
