### PR TITLE
update codeblocks

### PR DESCRIPTION
**Pull request by hhsnopek**
Moved my commit to a PR

### CODE REVIEW

**Comment by kylemac** [comment]
mind addressing #11 in this PR too? it won't be much extra effort and it'd go a long way.

**Comment by hhsnopek** [comment]
I actually have 2 PR's open one for this and another for codeblock styling see #13

**Comment by hhsnopek** [comment]
Did you want me to merge the 2 PRs ?

**Comment by kylemac** [comment]
ah! sorry. awesome work @hhsnopek. we'll get these merged in the AM. You're totally fine with having them as 2 separate PRs -- I just hadn't seen #13

**Comment by hhsnopek** [comment]
haha sounds good :smile: - when I meant merge I meant consolidate them, poor word choice on my end

**Pull request merged**
