### PR TITLE
[WIP] Updates mobile

### LINKED ISSUE #7: Mobile Navigation
When navigating on any device that is smaller than 605px, the nav bar disappears. I would like to create a hamburger menu for the smaller devices.

Update: The reason I'd like to add this is because it's hard to navigate the site without the nav bar

### PR DESCRIPTION
**Pull request by hhsnopek**
This PR cleans up the responsiveness of the site for mobile.

- [x] update document, articles, extensions links responsiveness
- [x] fix cloud position under 475px
- [x] fix logo overlapping for mobile
- [x] #7 Mobile Navigation

closes #7

### CODE REVIEW

**Comment by jenius** [comment]
Screenshotz?

**Comment by hhsnopek** [comment]
### Update links responsiveness just centers the links sooner.
Current: 
PR: 

### Fix cloud position under 475px (look at the right side) / fix logo overlapping
Current: 
PR:

**Comment by jenius** [comment]
:+1:

**Comment by hhsnopek** [comment]
This is all set @jenius

**Pull request merged**
